backend:
  name: git-gateway
  # repo: eeditiones/e-editiones-website
  branch: main
media_folder: "/img"
publish_mode: editorial_workflow
logo_url: https://e-editiones.org/img/e-editiones-logo-color.svg
site_url: https://e-editiones.org
display_url: https://e-editiones.org
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts/"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date", format: 'YYYY-MM-DD' }
      - { label: "short title", name: "short", widget: "string", required: false}
      - { label: "lead", name: "lead", widget: "text", required: false }
      - { label: "author", name: "author", widget: "string" }
      - { label: "tags", name: "tags", widget: "list", min: 1 }
      - { label: "cover image", name: "coverImage", widget: "image", required: false }
      - { label: "cover image credits", name: "coverImageCredits", widget: "text", required: false }
      - { label: "body", name: "body", widget: "markdown" }